NEW_NOTIFICATION_BUTTON: id=backoffice-backofficeNotification-newNotificationButton

TITLE_FIELD: id=backoffice-notification-titleField
VALIDATION_MSG_TITLE: id=backoffice-notification-titleField-helper-text
VALIDATION_MSG_EMPTY_TITLE_TEXT: Title is required!
VALIDATION_MSG_MAX_CHARS_TITLE_TEXT: Title cannot be longer than 256 characters!

CONTENT_FIELD: id=backoffice-notification-contentField
VALIDATION_MSG_CONTENT: id=backoffice-notification-contentField-helper-text
VALIDATION_MSG_EMPTY_CONTENT_TEXT: Subtitle or Content is required!
VALIDATION_MSG_MAX_CHARS_CONTENT_TEXT: Content cannot be longer than 256 characters!

NOTIF_TYPE_FIELD: id=backoffice-notification-notificationTypeField
VALIDATION_MSG_NOTIF_TYPE: id=backoffice-notification-notificationTypeField-helper-text
VALIDATION_MSG_EMPTY_NOTIF_TYPE_TEXT: Notification Type is required!
COUPON_OPTION_NOTIF_TYPE: id=menuItem-COUPON
INFORMATION_OPTION_NOTIF_TYPE: id=menuItem-INFORMATION

NOTIFICATION_URL_FIELD: id=backoffice-notification-notificationUrlField
VALIDATION_MSG_NOTIF_URL: id=backoffice-notification-notificationUrlField-helper-text
VALIDATION_MSG_EMPTY_NOTIF_URL_TEXT: Notification URL is required!
VALIDATION_MSG_NOTIFICATION_URL_FORMAT_TEXT: URL must include https!

COUPON_FIELD: id=backoffice-notification-couponTypeField
COUPON_DROPDOWN_CONTAINER: ul[aria-labelledby="backoffice-notification-couponTypeField-label"] li[role="option"]
VALIDATION_MSG_COUPON: id=backoffice-notification-couponTypeField-helper-text
VALIDATION_MSG_EMPTY_COUPON_TEXT: Coupon code is required

SEND_NOTIF_TYPE_FIELD: id=backoffice-notification-notificationSendTypesField
SEND_NOTIF_TYPE_DROPDOWN_CONTAINER: ul[aria-labelledby="backoffice-notification-notificationSendTypesField-label"] li[role="option"]
DAILY_OPTION_SEND_NOTIF_TYPE: id=menuItem-DAILY
ONCE_OPTION_SEND_NOTIF_TYPE: id=menuItem-ONCE
VALIDATION_MSG_SEND_NOTIF_TYPE: id=backoffice-notification-notificationSendTypesField-helper-text
VALIDATION_MSG_EMPTY_SEND_NOTIF_TYPE_TEXT: Send notification is required!

SEND_NOW_CHECKBOX: css=input[name="sendNow"]

PUSH_NOTIFICATION_IMAGE_FIELD: id=upload-image-backoffice-notification-imageUrl
VALIDATION_MSG_EMPTY_PUSH_NOTIFICATION_IMAGE_TEXT: Push Notification Image is required!

HOME_SCREEN_IMAGE_FIELD: id=upload-image-backoffice-notification-imageUrlLandscapeLogo
VALIDATION_MSG_EMPTY_HOME_SCREEN_IMAGE_TEXT: Home Screen Image Guide is required!

PREVIEW_BUTTON: id=icon-open-preview
DOWNLOAD_BUTTON: id=image-preview-backoffice-notification-imageUrl
IMAGE_PREVIEW_MODAL: id=img-preview

MODAL_MSG_NOTIF_TYPE_TEXT: Could not send push notification if notification type is COUPON or INFORMATION
MODAL_MSG_MAX_IMAGE_SIZE_TEXT: Image must be smaller than 1MB!

SAVE_BTN: id=backoffice-notification-saveButton
BACK_BTN: id=backoffice-notification-back-btn
